name: "CI Status Validation"
description: "Validate CI status workflow file"
inputs:
  token:
    required: true
  repo:
    required: true
  owner:
    required: true
  branch:
    required: true
outputs:
  result:
    description: Status of CI
runs:
  using: "node16"
  main: "dist/index.js"
